version: '3.7'

services:
  db:
    image: mysql:latest
    restart: "no"
    environment: 
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports: 
      - "${MYSQL_PORT}:${MYSQL_PORT}"