version: '3'

services:
  site:
    build:
      context: .
    container_name: "portfolio-site"
    ports:
      - "3000:3000"
    networks:
      - portfolio
    environment:
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
      NEXT_PUBLIC_API_TOKEN: "${NEXT_PUBLIC_API_TOKEN}"
networks:
  portfolio:
    driver: bridge
